sources:
  source_0:
    noise: 0.0
    type: gamma
    units: Sv/h
    value: 4845.5142309476
  source_1:
    noise: 0.0
    type: gamma
    units: Sv/h
    value: 7265.401017806063
  source_2:
    noise: 0.0
    type: gamma
    units: Sv/h
    value: 6346.80076564814
  source_3:
    noise: 0.0
    type: gamma
    units: Sv/h
    value: 7519.608060461759
  source_4:
    noise: 0.0
    type: gamma
    units: Sv/h
    value: 4906.468772325184
  source_5:
    noise: 0.0
    type: gamma
    units: Sv/h
    value: 2941.443642104072
  source_6:
    noise: 0.0
    type: gamma
    units: Sv/h
    value: 9138.312560323966
  source_7:
    noise: 0.0
    type: gamma
    units: Sv/h
    value: 8895.045969503937