sources:
  source_0:
    noise: 0.0
    type: gamma
    units: Sv/h
    value: 984.0021689024848
  source_1:
    noise: 0.0
    type: gamma
    units: Sv/h
    value: 9266.828502177696
  source_2:
    noise: 0.0
    type: gamma
    units: Sv/h
    value: 1925.743619604261
  source_3:
    noise: 0.0
    type: gamma
    units: Sv/h
    value: 2209.2253629290344
  source_4:
    noise: 0.0
    type: gamma
    units: Sv/h
    value: 6697.697211818655