sources:
  source_0:
    noise: 0.0
    type: gamma
    units: Sv/h
    value: 2850.6587291477804
  source_1:
    noise: 0.0
    type: gamma
    units: Sv/h
    value: 5902.894995288812
  source_2:
    noise: 0.0
    type: gamma
    units: Sv/h
    value: 6212.95964831393
  source_3:
    noise: 0.0
    type: gamma
    units: Sv/h
    value: 6611.742448247437